name: nftflex

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: v5.2.0  # OpenZeppelin contracts version

networks:
  ethereum:
    local:
      default_provider: anvil
      endpoint: http://127.0.0.1:8545

providers:
  anvil:
    host: http://127.0.0.1:8545
