name: nftflex

 # Docs -> https://docs.apeworx.io/ape/stable/userguides/config.html

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: v5.2.0  # OpenZeppelin contracts version

networks:
  ethereum:
    local:
      default_provider: test  # ✅ Use Ape's built-in test provider

# With test
# Everything works but with test we are getting an error 
# "Must be connected to a provider to use the token converter." happens because Ape Framework needs a provider for token conversions. This usually occurs when trying to interact with tokens (e.g., ERC-20) without a connected provider.
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5
  balance: 100_000 ETH
